@host = http://127.0.0.1:3500
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGhhdiIsImlhdCI6MTY4NjgxMjEyNCwiZXhwIjoxNjg2ODEyNDI0fQ.yV0an_9DydE9itEkC8vgr_rRgVzPxQMy7mFt30syDEc

// Register a New User
POST {{host}}/register
Content-Type: application/json

{
  "username": "rakesh",
  "password": "123456"
}

###
// Login User
POST {{host}}/auth
Content-Type: application/json

{
  "username": "madhav",
  "password": "123456"
}

###
// Refresh Token
GET {{host}}/refresh


###
// Logout
GET {{host}}/logout

###
// Get All Users
GET {{host}}/users
Authorization: Bearer {{accessToken}}

###
// Update User
PUT {{host}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "648ab5d626e43e284e3a5bcc",
  "username": "sandeep"
}

###
// Delete Users
DELETE  {{host}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "648ab5d626e43e284e3a5bcc"
}

###
// Create New User
POST {{host}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "sandeep",
  "password": "123456"
}